version: "3.3"

services:
  db:
    image: mongo:bionic
    ports:
      - 27017:27017
  # app:
  #   image: my-app:0.0.1-draft
  #   build: app
  #   environment:
  #     MONGO_HOST: db
  #   labels:
  #     - "traefik.backend=traefik"
  #     - "traefik.port=8181"
  #     - "traefik.frontend.rule=PathPrefixStrip:/myapp"
  # proxy:
  #   image: traefik:alpine
  #   command: >
  #     --web --docker --api
  #     --docker.domain=docker.local --docker.watch
  #     --accesslogsfile=/dev/stdout --logLevel=DEBUG
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/null:/traefik.toml
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
